apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: springboot-github-actions-quay-060625xxx 
  janus-idp.io/tekton: springboot-github-actions-quay-060625xxx
  backstage.io/kubernetes-id: springboot-github-actions-quay-060625xxx
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: springboot-github-actions-quay-060625xxx
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml