apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: springboot-github-actions-quay-060625xxx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: springboot-github-actions-quay-060625xxx 
  name: springboot-github-actions-quay-060625xxx
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: springboot-github-actions-quay-060625xxx
    weight: 100 
