apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: springboot-github-actions-quay-060625xxx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: springboot-github-actions-quay-060625xxx 
  name: springboot-github-actions-quay-060625xxx
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: springboot-github-actions-quay-060625xxx 
